{
    "objectName": "default",
    "displayName": "Default",
    "description": "Default surface for the Iron age world",

    "gameMap": {
        "border": "border.png",
        "border_highlighted": "border_highlighted.png",

        "plains": "terrainTypes/plains.png",
        "hills": "terrainTypes/hills.png",
        "forest": "terrainTypes/forest.png",
        "mountains": "terrainTypes/mountains.png",

        "village": "settlementTypes/village.png",
        "castle": "settlementTypes/castle.png",
        "city": "settlementTypes/city.png"
    },

    "miniMap": {
        "plains": "#39661e",
        "forest": "#173504",
        "hills": "#cbce16",
        "mountains": "#ce7516"
    },

    "tileSize": {
        "width": 110,
        "height": 128
    }
}
